--- #YAML:1.0
name:                Glib-EV
version:             2.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    EV:                            2
    ExtUtils::PkgConfig:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

configure_requires:
  ExtUtils::PkgConfig: 0
  EV: 2.0
    
