--- #YAML:1.0
name:                Glib-EV
version:             2.0
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    EV:                            2
    ExtUtils::PkgConfig:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2

configure_requires:
  ExtUtils::PkgConfig: 0
  EV: 2.0
    
